version: '3'

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  api:
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - '8888:8888/tcp'
    volumes:
      - .:/app
